# Generated by Django 5.0.6 on 2024-06-13 11:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('feshar', models.BooleanField(default=False)),
                ('deyabet', models.BooleanField(default=False)),
                ('tashanoj', models.BooleanField(default=False)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pationts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('do', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('paid', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('petient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='home.patient')),
            ],
        ),
    ]
