# Generated by Django 5.0.6 on 2024-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
