# Generated by Django 5.0.6 on 2024-06-13 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patientlist_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='paid',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
